# https://ci.appveyor.com/project/oblalex/il2fb-mission-parser

build: false # Not a C# project, build stuff at the test step instead.
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python27-x64"
    - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python34-x64"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - ps: Start-FileDownload 'https://bootstrap.pypa.io/get-pip.py' -FileName 'C:/get-pip.py'
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install -r ./requirements/ci.txt"
  - "%PYTHON%/Scripts/pip.exe install -e ."
test_script:
  - "%PYTHON%/Scripts/py.test"
